/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package medicine;

import Class.Medicine;
import javax.swing.JOptionPane;
import main.Home;

/**
 *
 * @author KXian
 */
public class MedicineModify extends javax.swing.JPanel {

    private Medicine oldMedicine;
    private Medicine medicine;
    private String staffName;
    private javax.swing.JFrame frame;
    
    /**
     * Creates new form MedicineModify
     */
    public MedicineModify() {
        initComponents();
    }
    
    public MedicineModify(String staffName, Medicine medicine, javax.swing.JFrame frame){
        initComponents();
        
        this.staffName = staffName;
        
        oldMedicine = new Medicine(medicine.getId(), medicine.getMedicineName(), medicine.getQuantity(), medicine.getUnitPrice(), medicine.getExpiredDate());
        this.medicine = medicine;
        
        this.frame = frame;
        
        //set the background to transparent
        oldNameTextField.setBackground(new java.awt.Color(0, 0, 0, 1));
        newNameTextField.setBackground(new java.awt.Color(0, 0, 0, 1));
        oldQuantityTextField.setBackground(new java.awt.Color(0, 0, 0, 1));
        quantityTextField.setBackground(new java.awt.Color(0, 0, 0, 1));
        oldUnitPriceTextField.setBackground(new java.awt.Color(0, 0, 0, 1));
        unitPriceTextField.setBackground(new java.awt.Color(0, 0, 0, 1));
        
        //Initialize patient old info
        oldNameTextField.setText(medicine.getMedicineName());
        oldQuantityTextField.setText(Integer.toString(medicine.getQuantity()));
        oldUnitPriceTextField.setText(Double.toString(medicine.getUnitPrice()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        modifyTitleLabel = new javax.swing.JLabel();
        medicineNameLabel = new javax.swing.JLabel();
        quantityLabel = new javax.swing.JLabel();
        unitPriceLabel = new javax.swing.JLabel();
        modifyBtn = new javax.swing.JButton();
        newNameTextField = new javax.swing.JTextField();
        quantityTextField = new javax.swing.JTextField();
        unitPriceTextField = new javax.swing.JTextField();
        oldNameTextField = new javax.swing.JTextField();
        oldQuantityTextField = new javax.swing.JTextField();
        oldUnitPriceTextField = new javax.swing.JTextField();
        icArrowLabel = new javax.swing.JLabel();
        icArrowLabel1 = new javax.swing.JLabel();
        icArrowLabel2 = new javax.swing.JLabel();
        cancelBtn1 = new javax.swing.JButton();

        modifyTitleLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        modifyTitleLabel.setText("Please Enter New Info For Modification");

        medicineNameLabel.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        medicineNameLabel.setText("Medicine Name : ");

        quantityLabel.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        quantityLabel.setText("Quantity : ");

        unitPriceLabel.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        unitPriceLabel.setText("Unit Price (RM) : ");

        modifyBtn.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        modifyBtn.setText("Modify");
        modifyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyBtnActionPerformed(evt);
            }
        });

        oldNameTextField.setEditable(false);

        oldQuantityTextField.setEditable(false);

        oldUnitPriceTextField.setEditable(false);

        icArrowLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/arrowRight.png"))); // NOI18N

        icArrowLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/arrowRight.png"))); // NOI18N

        icArrowLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/arrowRight.png"))); // NOI18N

        cancelBtn1.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        cancelBtn1.setText("Cancel");
        cancelBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(unitPriceLabel)
                    .addComponent(medicineNameLabel)
                    .addComponent(quantityLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(93, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(modifyTitleLabel)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(oldUnitPriceTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                            .addComponent(oldQuantityTextField))
                                        .addGap(12, 12, 12)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(icArrowLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(quantityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(icArrowLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(unitPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(oldNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(icArrowLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(newNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(83, 83, 83))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(modifyBtn)
                        .addGap(122, 122, 122))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(411, Short.MAX_VALUE)
                    .addComponent(cancelBtn1)
                    .addGap(29, 29, 29)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(modifyTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(medicineNameLabel)
                        .addComponent(oldNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(icArrowLabel)
                    .addComponent(newNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(quantityLabel)
                        .addComponent(quantityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(oldQuantityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(icArrowLabel1))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(unitPriceLabel)
                        .addComponent(unitPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(oldUnitPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(icArrowLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addComponent(modifyBtn)
                .addGap(21, 21, 21))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(326, Short.MAX_VALUE)
                    .addComponent(cancelBtn1)
                    .addGap(21, 21, 21)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void modifyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyBtnActionPerformed
        // TODO add your handling code here:
        boolean modifySuccess = false;
        
        //Medicine Name Only
        if(!newNameTextField.getText().equals("") && quantityTextField.getText().equals("") && unitPriceTextField.getText().equals("")){
                String name = newNameTextField.getText();
                
                medicine.setMedicineName(name);
                
                modifySuccess = true;
        }
        //Quantity Only
        else if(newNameTextField.getText().equals("") && !quantityTextField.getText().equals("") && unitPriceTextField.getText().equals("")){
            
            if(Integer.parseInt(quantityTextField.getText()) >= 0){
                
                medicine.setQuantity(Integer.parseInt(quantityTextField.getText()));
                
                modifySuccess = true;
                
            }else{
                
                JOptionPane.showMessageDialog(null, "Invalid Quantity, Please Enter Again !!!", "Invalid Quantity", JOptionPane.ERROR_MESSAGE);
            
            }
        }
        //Unit Price Only
        else if(newNameTextField.getText().equals("") && quantityTextField.getText().equals("") && !unitPriceTextField.getText().equals("")){
            
            if(Double.parseDouble(unitPriceTextField.getText()) > 0){
                
                medicine.setUnitPrice(Double.parseDouble(unitPriceTextField.getText()));
                
                modifySuccess = true;
                
            }else{
                
                JOptionPane.showMessageDialog(null, "Invalid Unit Price, Please Enter Again!!!", "Invalid Unit Price", JOptionPane.ERROR_MESSAGE);
                
            }
        }
        //Name, Quantity
        else if(!newNameTextField.getText().equals("") && !quantityTextField.getText().equals("") && unitPriceTextField.getText().equals("")){
            
            if(Integer.parseInt(quantityTextField.getText()) >= 0){
                String name = newNameTextField.getText();
                
                medicine.setMedicineName(name);
                medicine.setQuantity(Integer.parseInt(quantityTextField.getText()));
                
                modifySuccess = true;
                
            }else{
                JOptionPane.showMessageDialog(null, "Invalid Quantity, Please Enter Again !!!", "Invalid Quantity", JOptionPane.ERROR_MESSAGE);
            }
        }
        //Name, Unit Price
        else if(!newNameTextField.getText().equals("") && quantityTextField.getText().equals("") && !unitPriceTextField.getText().equals("")){
            
            if(Double.parseDouble(unitPriceTextField.getText()) > 0){
                String name = newNameTextField.getText();
                
                medicine.setMedicineName(name);
                medicine.setUnitPrice(Double.parseDouble(unitPriceTextField.getText()));
                
                modifySuccess = true;
                
            }
            else{
                JOptionPane.showMessageDialog(null, "Invalid Unit Price, Please Enter Again!!!", "Invalid Unit Price", JOptionPane.ERROR_MESSAGE);
            }
        }
        //Quantity, Unit Price
        else if(newNameTextField.getText().equals("") && !quantityTextField.getText().equals("") && !unitPriceTextField.getText().equals("")){
            
            if(Double.parseDouble(unitPriceTextField.getText()) > 0 && Integer.parseInt(quantityTextField.getText()) >= 0){
                
                medicine.setUnitPrice(Double.parseDouble(unitPriceTextField.getText()));
                medicine.setQuantity(Integer.parseInt(quantityTextField.getText()));
                
                modifySuccess = true;
                
            }else{
                
                if(Double.parseDouble(unitPriceTextField.getText()) <= 0){
                    
                    JOptionPane.showMessageDialog(null, "Invalid Unit Price, Please Enter Again!!!", "Invalid Unit Price", JOptionPane.ERROR_MESSAGE);
                    
                }
                
                if(Integer.parseInt(quantityTextField.getText()) < 0){
                    
                    JOptionPane.showMessageDialog(null, "Invalid Quantity, Please Enter Again !!!", "Invalid Quantity", JOptionPane.ERROR_MESSAGE);
                    
                }
                
            }
        }
        //Name, Quantity, Unit Price
        else if(!newNameTextField.getText().equals("") && !quantityTextField.getText().equals("") && !unitPriceTextField.getText().equals("")){
            
            if(Double.parseDouble(unitPriceTextField.getText()) > 0 && Integer.parseInt(quantityTextField.getText()) >= 0){
                String name = newNameTextField.getText();
                
                medicine.setMedicineName(name);
                medicine.setUnitPrice(Double.parseDouble(unitPriceTextField.getText()));
                medicine.setQuantity(Integer.parseInt(quantityTextField.getText()));
                
                modifySuccess = true;
                
            }else{
                
                if(Double.parseDouble(unitPriceTextField.getText()) <= 0){
                    
                    JOptionPane.showMessageDialog(null, "Invalid Unit Price, Please Enter Again!!!", "Invalid Unit Price", JOptionPane.ERROR_MESSAGE);
                    
                }
                
                if(Integer.parseInt(quantityTextField.getText()) < 0){
                    
                    JOptionPane.showMessageDialog(null, "Invalid Quantity, Please Enter Again !!!", "Invalid Quantity", JOptionPane.ERROR_MESSAGE);
                    
                }
                
            }
        }
        //No Input
        else if(newNameTextField.getText().equals("") && quantityTextField.getText().equals("") && unitPriceTextField.getText().equals("")){
            
            JOptionPane.showMessageDialog(null, "Please Enter Name / Quantity / Unit Price of Medicine to modify !!!", "Invalid Input", JOptionPane.ERROR_MESSAGE);
            
        }
        
        if(modifySuccess){
            Home home = new Home(staffName, oldMedicine, medicine);
            home.setVisible(true);
            frame.dispose();
            //this.dispose();
        }
    }//GEN-LAST:event_modifyBtnActionPerformed

    private void cancelBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtn1ActionPerformed
        Home home = new Home(staffName, oldMedicine, medicine);
        home.setVisible(true);
        frame.dispose();
        //this.dispose();
    }//GEN-LAST:event_cancelBtn1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn1;
    private javax.swing.JLabel icArrowLabel;
    private javax.swing.JLabel icArrowLabel1;
    private javax.swing.JLabel icArrowLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel medicineNameLabel;
    private javax.swing.JButton modifyBtn;
    private javax.swing.JLabel modifyTitleLabel;
    private javax.swing.JTextField newNameTextField;
    private javax.swing.JTextField oldNameTextField;
    private javax.swing.JTextField oldQuantityTextField;
    private javax.swing.JTextField oldUnitPriceTextField;
    private javax.swing.JLabel quantityLabel;
    private javax.swing.JTextField quantityTextField;
    private javax.swing.JLabel unitPriceLabel;
    private javax.swing.JTextField unitPriceTextField;
    // End of variables declaration//GEN-END:variables
}
