
import java.awt.Color;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.WindowEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;
import javax.swing.JPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class Home extends javax.swing.JFrame {

    private SideBarListener sideBarListener = new SideBarListener();
    
    /**
     * Creates new form Home
     */
    public Home(String username) {
        initComponents();
        setLocationRelativeTo(null);
        patientHoverPanel.setBackground( new Color(2, 165, 249));
        patientBar.setBackground( new Color(63, 218, 234));
        
        greetLabel.setText(greetLabel.getText() + username);
        
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("dd-MM-yyyy");
        dateLabel.setText(dateLabel.getText() + s.format(d));
        
        showTime();
    }

    public void showTime(){
        new Timer(0, new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss a");
                timeLabel.setText(s.format(d));
            }
            
        }).start();
    }
    
    static int xx, yy; 
    private class SideBarListener implements MouseListener{

        @Override
        public void mouseClicked(MouseEvent e) {
            if(e.getSource() == patientBar){
                patientsModule.setVisible(true);
                appointmentsModule.setVisible(false);
                medicineModule.setVisible(false);
                staffModule.setVisible(false);
            }
            
            if(e.getSource() == appointmentsBar){
                patientsModule.setVisible(false);
                appointmentsModule.setVisible(true);
                medicineModule.setVisible(false);
                staffModule.setVisible(false);
            }
            
            if(e.getSource() == medicineBar){
                patientsModule.setVisible(false);
                appointmentsModule.setVisible(false);
                medicineModule.setVisible(true);
                staffModule.setVisible(false);
            }
            
            if(e.getSource() == staffBar){
                patientsModule.setVisible(false);
                appointmentsModule.setVisible(false);
                medicineModule.setVisible(false);
                staffModule.setVisible(true);
            }
        }

        @Override
        public void mousePressed(MouseEvent e) {
            throw new UnsupportedOperationException("Not supported yet."); 
        }

        @Override
        public void mouseReleased(MouseEvent e) {
            throw new UnsupportedOperationException("Not supported yet."); 
        }

        @Override
        public void mouseEntered(MouseEvent e) {
            JPanel panel = (JPanel)e.getSource(); 
            Component[] label = panel.getComponents();
            label[0].setBackground( new Color(2, 165, 249));
            panel.setBackground( new Color(63, 218, 234));
            
        }

        @Override
        public void mouseExited(MouseEvent e) {
            JPanel panel = (JPanel)e.getSource();
            Component[] label = panel.getComponents();
            label[0].setBackground( new Color(255, 255, 255));
            panel.setBackground( new Color(255, 255, 255));
        }

        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topPanel = new javax.swing.JPanel();
        logoPanel = new javax.swing.JPanel();
        clinicLogo = new javax.swing.JLabel();
        closeLabel = new javax.swing.JLabel();
        greetLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        timeTitle = new javax.swing.JLabel();
        timeLabel = new javax.swing.JLabel();
        sidePanel = new javax.swing.JPanel();
        patientBar = new javax.swing.JPanel();
        patientLogo = new javax.swing.JLabel();
        patientLabel = new javax.swing.JLabel();
        patientHoverPanel = new javax.swing.JPanel();
        appointmentsBar = new javax.swing.JPanel();
        appointmentsLogo = new javax.swing.JLabel();
        appointmentsLabel = new javax.swing.JLabel();
        appointmentsHoverPanel = new javax.swing.JPanel();
        medicineBar = new javax.swing.JPanel();
        medicineLogo = new javax.swing.JLabel();
        medicineLabel = new javax.swing.JLabel();
        medicineHoverPanel = new javax.swing.JPanel();
        staffBar = new javax.swing.JPanel();
        staffLogo = new javax.swing.JLabel();
        staffLabel = new javax.swing.JLabel();
        staffHoverPanel = new javax.swing.JPanel();
        methodPanel = new javax.swing.JPanel();
        patientsModule = new javax.swing.JPanel();
        patientsModuleLabel = new javax.swing.JLabel();
        appointmentsModule = new javax.swing.JPanel();
        appointmentsModuleLabel = new javax.swing.JLabel();
        medicineModule = new javax.swing.JPanel();
        medicineModuleLabel = new javax.swing.JLabel();
        staffModule = new javax.swing.JPanel();
        staffModuleLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        topPanel.setBackground(new java.awt.Color(255, 255, 255));
        topPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                topPanelMouseDragged(evt);
            }
        });
        topPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                topPanelMousePressed(evt);
            }
        });

        logoPanel.setBackground(new java.awt.Color(2, 188, 249));

        clinicLogo.setFont(new java.awt.Font(".Heiti J", 1, 20)); // NOI18N
        clinicLogo.setForeground(new java.awt.Color(255, 255, 255));
        clinicLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clinicLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/hospital.png"))); // NOI18N
        clinicLogo.setText("Klinik K.J Lim");

        javax.swing.GroupLayout logoPanelLayout = new javax.swing.GroupLayout(logoPanel);
        logoPanel.setLayout(logoPanelLayout);
        logoPanelLayout.setHorizontalGroup(
            logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(clinicLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
        );
        logoPanelLayout.setVerticalGroup(
            logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(clinicLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        closeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cancel.png"))); // NOI18N
        closeLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeLabelMouseClicked(evt);
            }
        });

        greetLabel.setFont(new java.awt.Font(".Heiti J", 1, 24)); // NOI18N
        greetLabel.setForeground(new java.awt.Color(51, 51, 51));
        greetLabel.setText("Welcome, ");

        dateLabel.setFont(new java.awt.Font(".Heiti J", 1, 14)); // NOI18N
        dateLabel.setForeground(new java.awt.Color(51, 51, 51));
        dateLabel.setText("Date: ");

        timeTitle.setFont(new java.awt.Font(".Heiti J", 1, 14)); // NOI18N
        timeTitle.setForeground(new java.awt.Color(51, 51, 51));
        timeTitle.setText("Time: ");

        timeLabel.setFont(new java.awt.Font(".Heiti J", 1, 14)); // NOI18N
        timeLabel.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addComponent(logoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(greetLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(236, 236, 236)
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(dateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, topPanelLayout.createSequentialGroup()
                        .addComponent(timeTitle)
                        .addGap(0, 0, 0)
                        .addComponent(timeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 0, 0)
                .addComponent(closeLabel)
                .addGap(0, 0, 0))
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(greetLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(topPanelLayout.createSequentialGroup()
                        .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(closeLabel))
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(timeTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                            .addComponent(timeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
        );

        sidePanel.setBackground(new java.awt.Color(255, 255, 255));

        patientBar.setBackground(new java.awt.Color(255, 255, 255));
        patientBar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        patientBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                patientBarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                patientBarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                patientBarMouseExited(evt);
            }
        });

        patientLogo.setForeground(new java.awt.Color(255, 255, 255));
        patientLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        patientLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pulse.png"))); // NOI18N

        patientLabel.setFont(new java.awt.Font(".Heiti J", 0, 18)); // NOI18N
        patientLabel.setForeground(new java.awt.Color(0, 0, 0));
        patientLabel.setText("Patients");

        patientHoverPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout patientHoverPanelLayout = new javax.swing.GroupLayout(patientHoverPanel);
        patientHoverPanel.setLayout(patientHoverPanelLayout);
        patientHoverPanelLayout.setHorizontalGroup(
            patientHoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        patientHoverPanelLayout.setVerticalGroup(
            patientHoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout patientBarLayout = new javax.swing.GroupLayout(patientBar);
        patientBar.setLayout(patientBarLayout);
        patientBarLayout.setHorizontalGroup(
            patientBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patientBarLayout.createSequentialGroup()
                .addComponent(patientHoverPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(patientLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(patientLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        patientBarLayout.setVerticalGroup(
            patientBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(patientLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(patientLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(patientHoverPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        appointmentsBar.setBackground(new java.awt.Color(255, 255, 255));
        appointmentsBar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        appointmentsBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                appointmentsBarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                appointmentsBarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                appointmentsBarMouseExited(evt);
            }
        });

        appointmentsLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        appointmentsLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/appointment.png"))); // NOI18N

        appointmentsLabel.setFont(new java.awt.Font(".Heiti J", 0, 18)); // NOI18N
        appointmentsLabel.setForeground(new java.awt.Color(0, 0, 0));
        appointmentsLabel.setText("Appointments");

        appointmentsHoverPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout appointmentsHoverPanelLayout = new javax.swing.GroupLayout(appointmentsHoverPanel);
        appointmentsHoverPanel.setLayout(appointmentsHoverPanelLayout);
        appointmentsHoverPanelLayout.setHorizontalGroup(
            appointmentsHoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        appointmentsHoverPanelLayout.setVerticalGroup(
            appointmentsHoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout appointmentsBarLayout = new javax.swing.GroupLayout(appointmentsBar);
        appointmentsBar.setLayout(appointmentsBarLayout);
        appointmentsBarLayout.setHorizontalGroup(
            appointmentsBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(appointmentsBarLayout.createSequentialGroup()
                .addComponent(appointmentsHoverPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(appointmentsLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(appointmentsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        appointmentsBarLayout.setVerticalGroup(
            appointmentsBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(appointmentsLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(appointmentsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(appointmentsHoverPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        medicineBar.setBackground(new java.awt.Color(255, 255, 255));
        medicineBar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        medicineBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                medicineBarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                medicineBarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                medicineBarMouseExited(evt);
            }
        });

        medicineLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        medicineLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/drugs.png"))); // NOI18N

        medicineLabel.setFont(new java.awt.Font(".Heiti J", 0, 18)); // NOI18N
        medicineLabel.setForeground(new java.awt.Color(0, 0, 0));
        medicineLabel.setText("Medicine");

        medicineHoverPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout medicineHoverPanelLayout = new javax.swing.GroupLayout(medicineHoverPanel);
        medicineHoverPanel.setLayout(medicineHoverPanelLayout);
        medicineHoverPanelLayout.setHorizontalGroup(
            medicineHoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        medicineHoverPanelLayout.setVerticalGroup(
            medicineHoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout medicineBarLayout = new javax.swing.GroupLayout(medicineBar);
        medicineBar.setLayout(medicineBarLayout);
        medicineBarLayout.setHorizontalGroup(
            medicineBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(medicineBarLayout.createSequentialGroup()
                .addComponent(medicineHoverPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(medicineLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(medicineLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        medicineBarLayout.setVerticalGroup(
            medicineBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(medicineLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(medicineLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(medicineHoverPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        staffBar.setBackground(new java.awt.Color(255, 255, 255));
        staffBar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        staffBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                staffBarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                staffBarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                staffBarMouseExited(evt);
            }
        });

        staffLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        staffLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/nurse.png"))); // NOI18N

        staffLabel.setFont(new java.awt.Font(".Heiti J", 0, 18)); // NOI18N
        staffLabel.setForeground(new java.awt.Color(0, 0, 0));
        staffLabel.setText("Staff");

        staffHoverPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout staffHoverPanelLayout = new javax.swing.GroupLayout(staffHoverPanel);
        staffHoverPanel.setLayout(staffHoverPanelLayout);
        staffHoverPanelLayout.setHorizontalGroup(
            staffHoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        staffHoverPanelLayout.setVerticalGroup(
            staffHoverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout staffBarLayout = new javax.swing.GroupLayout(staffBar);
        staffBar.setLayout(staffBarLayout);
        staffBarLayout.setHorizontalGroup(
            staffBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(staffBarLayout.createSequentialGroup()
                .addComponent(staffHoverPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(staffLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(staffLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        staffBarLayout.setVerticalGroup(
            staffBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(staffLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(staffLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(staffHoverPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(patientBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(appointmentsBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(medicineBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(staffBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        sidePanelLayout.setVerticalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(patientBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(appointmentsBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(medicineBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(staffBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        methodPanel.setBackground(new java.awt.Color(240, 240, 240));
        methodPanel.setLayout(new java.awt.CardLayout());

        patientsModule.setBackground(new java.awt.Color(102, 102, 255));

        patientsModuleLabel.setFont(new java.awt.Font(".Heiti J", 1, 24)); // NOI18N
        patientsModuleLabel.setForeground(new java.awt.Color(51, 51, 51));
        patientsModuleLabel.setText("Patients Module");
        patientsModuleLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 1, 0));

        javax.swing.GroupLayout patientsModuleLayout = new javax.swing.GroupLayout(patientsModule);
        patientsModule.setLayout(patientsModuleLayout);
        patientsModuleLayout.setHorizontalGroup(
            patientsModuleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patientsModuleLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(patientsModuleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(525, Short.MAX_VALUE))
        );
        patientsModuleLayout.setVerticalGroup(
            patientsModuleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patientsModuleLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(patientsModuleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(457, Short.MAX_VALUE))
        );

        methodPanel.add(patientsModule, "card2");

        appointmentsModule.setBackground(new java.awt.Color(255, 51, 204));

        appointmentsModuleLabel.setFont(new java.awt.Font(".Heiti J", 1, 24)); // NOI18N
        appointmentsModuleLabel.setForeground(new java.awt.Color(51, 51, 51));
        appointmentsModuleLabel.setText("Appointments Module");
        appointmentsModuleLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 1, 0));

        javax.swing.GroupLayout appointmentsModuleLayout = new javax.swing.GroupLayout(appointmentsModule);
        appointmentsModule.setLayout(appointmentsModuleLayout);
        appointmentsModuleLayout.setHorizontalGroup(
            appointmentsModuleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(appointmentsModuleLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(appointmentsModuleLabel)
                .addContainerGap(476, Short.MAX_VALUE))
        );
        appointmentsModuleLayout.setVerticalGroup(
            appointmentsModuleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(appointmentsModuleLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(appointmentsModuleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(457, Short.MAX_VALUE))
        );

        methodPanel.add(appointmentsModule, "card3");

        medicineModule.setBackground(new java.awt.Color(255, 255, 0));

        medicineModuleLabel.setFont(new java.awt.Font(".Heiti J", 1, 24)); // NOI18N
        medicineModuleLabel.setForeground(new java.awt.Color(51, 51, 51));
        medicineModuleLabel.setText("Medicine Module");
        medicineModuleLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 1, 0));

        javax.swing.GroupLayout medicineModuleLayout = new javax.swing.GroupLayout(medicineModule);
        medicineModule.setLayout(medicineModuleLayout);
        medicineModuleLayout.setHorizontalGroup(
            medicineModuleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(medicineModuleLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(medicineModuleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(525, Short.MAX_VALUE))
        );
        medicineModuleLayout.setVerticalGroup(
            medicineModuleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(medicineModuleLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(medicineModuleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(457, Short.MAX_VALUE))
        );

        methodPanel.add(medicineModule, "card4");

        staffModule.setBackground(new java.awt.Color(102, 255, 102));

        staffModuleLabel.setFont(new java.awt.Font(".Heiti J", 1, 24)); // NOI18N
        staffModuleLabel.setForeground(new java.awt.Color(51, 51, 51));
        staffModuleLabel.setText("Staff Module");
        staffModuleLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 1, 0));

        javax.swing.GroupLayout staffModuleLayout = new javax.swing.GroupLayout(staffModule);
        staffModule.setLayout(staffModuleLayout);
        staffModuleLayout.setHorizontalGroup(
            staffModuleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(staffModuleLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(staffModuleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(525, Short.MAX_VALUE))
        );
        staffModuleLayout.setVerticalGroup(
            staffModuleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(staffModuleLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(staffModuleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(457, Short.MAX_VALUE))
        );

        methodPanel.add(staffModule, "card5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(methodPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(topPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(topPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(methodPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void staffBarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_staffBarMouseExited
        // TODO add your handling code here:
        sideBarListener.mouseExited(evt);
    }//GEN-LAST:event_staffBarMouseExited

    private void staffBarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_staffBarMouseEntered
        // TODO add your handling code here:
        sideBarListener.mouseEntered(evt);
    }//GEN-LAST:event_staffBarMouseEntered

    private void medicineBarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_medicineBarMouseExited
        // TODO add your handling code here:
        sideBarListener.mouseExited(evt);
    }//GEN-LAST:event_medicineBarMouseExited

    private void medicineBarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_medicineBarMouseEntered
        // TODO add your handling code here:
        sideBarListener.mouseEntered(evt);
    }//GEN-LAST:event_medicineBarMouseEntered

    private void appointmentsBarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_appointmentsBarMouseExited
        // TODO add your handling code here:
        sideBarListener.mouseExited(evt);
    }//GEN-LAST:event_appointmentsBarMouseExited

    private void appointmentsBarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_appointmentsBarMouseEntered
        // TODO add your handling code here:
        sideBarListener.mouseEntered(evt);
    }//GEN-LAST:event_appointmentsBarMouseEntered

    private void patientBarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_patientBarMouseExited
        // TODO add your handling code here:
        sideBarListener.mouseExited(evt);
    }//GEN-LAST:event_patientBarMouseExited

    private void patientBarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_patientBarMouseEntered
        // TODO add your handling code here:
        sideBarListener.mouseEntered(evt);
    }//GEN-LAST:event_patientBarMouseEntered

    private void topPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topPanelMousePressed
        // TODO add your handling code here:
        xx = evt.getX();
        yy = evt.getY();
    }//GEN-LAST:event_topPanelMousePressed

    private void topPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topPanelMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x-xx, y-yy);
    }//GEN-LAST:event_topPanelMouseDragged

    private void closeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLabelMouseClicked
        // TODO add your handling code here:
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_closeLabelMouseClicked

    private void patientBarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_patientBarMouseClicked
        // TODO add your handling code here:
        sideBarListener.mouseClicked(evt);
    }//GEN-LAST:event_patientBarMouseClicked

    private void appointmentsBarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_appointmentsBarMouseClicked
        // TODO add your handling code here:
        sideBarListener.mouseClicked(evt);
    }//GEN-LAST:event_appointmentsBarMouseClicked

    private void medicineBarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_medicineBarMouseClicked
        // TODO add your handling code here:
        sideBarListener.mouseClicked(evt);
    }//GEN-LAST:event_medicineBarMouseClicked

    private void staffBarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_staffBarMouseClicked
        // TODO add your handling code here:
        sideBarListener.mouseClicked(evt);
    }//GEN-LAST:event_staffBarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel appointmentsBar;
    private javax.swing.JPanel appointmentsHoverPanel;
    private javax.swing.JLabel appointmentsLabel;
    private javax.swing.JLabel appointmentsLogo;
    private javax.swing.JPanel appointmentsModule;
    private javax.swing.JLabel appointmentsModuleLabel;
    private javax.swing.JLabel clinicLogo;
    private javax.swing.JLabel closeLabel;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JLabel greetLabel;
    private javax.swing.JPanel logoPanel;
    private javax.swing.JPanel medicineBar;
    private javax.swing.JPanel medicineHoverPanel;
    private javax.swing.JLabel medicineLabel;
    private javax.swing.JLabel medicineLogo;
    private javax.swing.JPanel medicineModule;
    private javax.swing.JLabel medicineModuleLabel;
    private javax.swing.JPanel methodPanel;
    private javax.swing.JPanel patientBar;
    private javax.swing.JPanel patientHoverPanel;
    private javax.swing.JLabel patientLabel;
    private javax.swing.JLabel patientLogo;
    private javax.swing.JPanel patientsModule;
    private javax.swing.JLabel patientsModuleLabel;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JPanel staffBar;
    private javax.swing.JPanel staffHoverPanel;
    private javax.swing.JLabel staffLabel;
    private javax.swing.JLabel staffLogo;
    private javax.swing.JPanel staffModule;
    private javax.swing.JLabel staffModuleLabel;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JLabel timeTitle;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables
}
