
package patient;

import main.Home;
import Class.*;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;

public class PatientDiagnose extends javax.swing.JFrame {
    private List<Patient> patientOnHoldList = new ArrayList<>();
    private Patient oldPatient;
    private Patient patient;
    private String staffName;
    private javax.swing.JFrame frame;
    
    SimpleDateFormat s = new SimpleDateFormat("dd-MM-yyyy");
    Date d = new Date();
    
    /**
     * Creates new form PatientDiagnose
     */
    public PatientDiagnose() {
        initComponents();
    }
    
    public PatientDiagnose(String staffName, Patient patient, javax.swing.JFrame frame, List<Patient> patientOnHoldList) {
        initComponents();
        
        this.staffName = staffName;
        
        oldPatient = new Patient(patient.getIcNo(), patient.getIc(), patient.getName(), patient.getMobileNo(), patient.getDateCreated(), patient.getMedicalDescription());
        this.patient = patient;
        
        this.frame = frame;
        this.patientOnHoldList = patientOnHoldList;

        this.patientDiagnoseTitleLabel.setText(this.patientDiagnoseTitleLabel.getText() + this.patient.getName());
        
        if(this.patient.getMedicalDescription() == null){
            
            this.patientDiagnoseMedicalDescriptionTextArea.setText(s.format(d) + "\n");
            
        }else{
            
            this.patientDiagnoseMedicalDescriptionTextArea.setText(this.patient.getMedicalDescription() + "\n" + s.format(d) + "\n");
        
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        patientDiagnoseTitleLabel = new javax.swing.JLabel();
        patientDiagnoseMedicalDescriptionScrollPane = new javax.swing.JScrollPane();
        patientDiagnoseMedicalDescriptionTextArea = new javax.swing.JTextArea();
        patientDiagnoseMedicalDescriptionLabel = new javax.swing.JLabel();
        patientDiagnoseEditButton = new javax.swing.JButton();
        patientDiagnoseCancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Patient Diagnose");

        patientDiagnoseTitleLabel.setFont(new java.awt.Font(".Heiti J", 1, 24)); // NOI18N
        patientDiagnoseTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        patientDiagnoseTitleLabel.setText("Diagnose of ");

        patientDiagnoseMedicalDescriptionTextArea.setColumns(20);
        patientDiagnoseMedicalDescriptionTextArea.setRows(5);
        patientDiagnoseMedicalDescriptionScrollPane.setViewportView(patientDiagnoseMedicalDescriptionTextArea);

        patientDiagnoseMedicalDescriptionLabel.setFont(new java.awt.Font(".Heiti J", 1, 18)); // NOI18N
        patientDiagnoseMedicalDescriptionLabel.setText("Medical Description");
        patientDiagnoseMedicalDescriptionLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        patientDiagnoseEditButton.setFont(new java.awt.Font(".Heiti J", 1, 14)); // NOI18N
        patientDiagnoseEditButton.setText("Edit");
        patientDiagnoseEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientDiagnoseEditButtonActionPerformed(evt);
            }
        });

        patientDiagnoseCancelButton.setFont(new java.awt.Font(".Heiti J", 1, 14)); // NOI18N
        patientDiagnoseCancelButton.setText("Cancel");
        patientDiagnoseCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientDiagnoseCancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(patientDiagnoseTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(patientDiagnoseEditButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(patientDiagnoseCancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(patientDiagnoseMedicalDescriptionScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(patientDiagnoseMedicalDescriptionLabel))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(patientDiagnoseTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(patientDiagnoseMedicalDescriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(patientDiagnoseMedicalDescriptionScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientDiagnoseCancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patientDiagnoseEditButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void patientDiagnoseEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientDiagnoseEditButtonActionPerformed
        // TODO add your handling code here:
        this.patient.setMedicalDescription(this.patientDiagnoseMedicalDescriptionTextArea.getText());
        
        JOptionPane.showMessageDialog(null, "Successfully Edited Patient Medical Description", "Medical Description", JOptionPane.INFORMATION_MESSAGE);
        
        System.out.println(this.patient.getMedicalDescription());
        
        Home home = new Home(staffName, oldPatient, patient, patientOnHoldList);
        home.setVisible(true);
        frame.dispose();
        this.dispose();
    }//GEN-LAST:event_patientDiagnoseEditButtonActionPerformed

    private void patientDiagnoseCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientDiagnoseCancelButtonActionPerformed
        // TODO add your handling code here:
        
        JOptionPane.showMessageDialog(null, "Cancel Edit Patient Medical Description", "Medical Description", JOptionPane.INFORMATION_MESSAGE);
        
        Home home = new Home(staffName, patientOnHoldList);
        home.setVisible(true);
        frame.dispose();
        this.dispose();
    }//GEN-LAST:event_patientDiagnoseCancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientDiagnose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientDiagnose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientDiagnose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientDiagnose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientDiagnose().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton patientDiagnoseCancelButton;
    private javax.swing.JButton patientDiagnoseEditButton;
    private javax.swing.JLabel patientDiagnoseMedicalDescriptionLabel;
    private javax.swing.JScrollPane patientDiagnoseMedicalDescriptionScrollPane;
    private javax.swing.JTextArea patientDiagnoseMedicalDescriptionTextArea;
    private javax.swing.JLabel patientDiagnoseTitleLabel;
    // End of variables declaration//GEN-END:variables
}
